// RoomIndex.json
export const Room1 = () => import('./Room1.json');
export const Room2 = () => import('./Room2.json');
export const Room3 = () => import('./Room3.json');
export const Room4 = () => import('./Room4.json');
export const Room5 = () => import('./Room5.json');
export const Room6 = () => import('./Room6.json');
export const Room7 = () => import('./Room7.json');
export const Room8 = () => import('./Room8.json');
export const Room9 = () => import('./Room9.json');
export const Room10 = () => import('./Room10.json');
export const Room11 = () => import('./Room11.json');
export const Room12 = () => import('./Room12.json');
export const Room13 = () => import('./Room13.json');
export const Room14 = () => import('./Room14.json');
export const Room15 = () => import('./Room15.json');
export const Room16 = () => import('./Room16.json');
export const Room17 = () => import('./Room17.json');
export const Room18 = () => import('./Room18.json');
// export const Room19 = () => import('./Room19.json');
// export const Room20 = () => import('./Room20.json');
